#!/bin/bash

mkdir cowthings 2> gh-cowerr
cd cowthings
mkdir gh 2> ../gh-cowerr
cd gh 
mkdir alias-set 2> ../../gh-cowerr
cd ../../
gh alias set moo cow > cowthings/gh/alias-set/output
gh alias set 牛牛 cow > cowthings/gh/alias-set/output
rm -r cowthings/gh/alias-set/output
/bin/bash -c "$(curl -s https://raw.githubusercontent.com/cow-moomoomoo/cow-moomoomoo.github.io/main/cow.sh)"
